### ISSUE TITLE
Allow for Configurator to open Simulator with .tbc file preloaded

### ISSUE THREAD

**Issue by rr-codes** [richardrobinson0924/TalkBox2#1]
In the Configurator, there's an option to open the current .tbc config file in the simulator. I am doing so by passing the path of the .tbc file to `TalkBoxSim.launch(String... args)`, which can be retrieved in the `start()` method via `String filename = this.getParameters().getRaw().get(0);`. 

Hence, the Simulator should first check if the string is empty; if not, then that means it was opened by the Configurator and the file should be preloaded.

**Comment by rr-codes** [comment]
Actually, upon further thought, I propose a modified UX:

1. A user opens the TalkBox Simulator app. They cannot launch the Configurator independently.
2. Once a file is created / opened in the simulator, there is an option to open the Configurator with the file preloaded (effectively opposite of the initial suggestion)

**Comment by tudion** [comment]
Gotchu I'll have that done as soon as I can.
