### ISSUE TITLE
Multiple things that need to be done ASAP

### ISSUE THREAD

**Issue by rr-codes** [richardrobinson0924/TalkBox2#4]
- Custom / Play button should not be inline with the rest of the buttons
- buttons should not have labels (see JavaDoc on how the device work)
- buttons need to play audio
- menu bar
- open Config app
- make sure it works fine for >4 buttons

**Comment by rr-codes** [comment]
@ashishranjanth @tudion how's progress on these going?

**Comment by tudion** [comment]
stressful as ever hahaha. I could probably get the simulator to switch to the configurator, but i don't think i could get the operations part done in time
